// server/redactor_ia/services/countryProfiles_latinamerica.js
module.exports = {
  'Cuba': {
    code: 'CU', region: 'Caribe',
    city_style: 'Ciudad caribeña colonial con edificios bajos coloridos, balcones de hierro forjado',
    architecture: 'Colonial española, art déco tropical, arquitectura soviética años 60-80',
    climate: 'Tropical cálido, húmedo, luz solar intensa',
    people_style: 'Población caribeña diversa, vestimenta informal colorida',
    environment: 'Malecón, palmeras, vegetación tropical, autos clásicos',
    colors: 'Azul turquesa, amarillo, rosa coral, verde lima',
    flags_allowed: ['bandera cubana (azul, blanco, rojo con estrella)'],
    flags_forbidden: ['bandera estadounidense', 'bandera china', 'bandera rusa'],
    skyline_forbidden: ['Manhattan', 'Miami', 'Moscú']
  },
  'Venezuela': {
    code: 'VE', region: 'Sudamérica',
    city_style: 'Ciudad caribeña-andina con torres de apartamentos, barrios en colinas',
    architecture: 'Modernista años 60-70, torres residenciales, ranchos en laderas',
    climate: 'Tropical cálido',
    people_style: 'Población diversa mestiza',
    environment: 'Montañas cercanas, vegetación tropical, barrios en colinas',
    colors: 'Terracota, amarillo, azul caribeño',
    flags_allowed: ['bandera venezolana (amarillo, azul, rojo con estrellas)'],
    flags_forbidden: ['bandera colombiana', 'bandera cubana'],
    skyline_forbidden: ['Bogotá', 'Ciudad de México']
  },
  'México': {
    code: 'MX', region: 'América del Norte',
    city_style: 'Metrópolis extensa con zonas coloniales y rascacielos modernos',
    architecture: 'Colonial española, modernista mexicano, arquitectura prehispánica',
    climate: 'Variado: tropical en costas, templado en altiplano',
    people_style: 'Población mestiza diversa, presencia indígena',
    environment: 'Montañas volcánicas, agaves, plazas amplias, mercados',
    colors: 'Rosa mexicano, amarillo mostaza, azul añil, terracota',
    flags_allowed: ['bandera mexicana (verde, blanco, rojo con águila)'],
    flags_forbidden: ['bandera estadounidense', 'bandera guatemalteca'],
    skyline_forbidden: ['Nueva York', 'Los Ángeles']
  },
  'Colombia': {
    code: 'CO', region: 'Sudamérica',
    city_style: 'Ciudades andinas modernas con zonas coloniales',
    architecture: 'Colonial española, modernista, ladrillo rojo',
    climate: 'Andino templado, tropical en costas',
    people_style: 'Población diversa mestiza, afrodescendiente',
    environment: 'Montañas andinas verdes, valles, cafetales',
    colors: 'Verde esmeralda, amarillo café, azul montaña',
    flags_allowed: ['bandera colombiana (amarillo, azul, rojo)'],
    flags_forbidden: ['bandera venezolana', 'bandera ecuatoriana'],
    skyline_forbidden: ['Caracas', 'Quito']
  },
  'Argentina': {
    code: 'AR', region: 'Sudamérica',
    city_style: 'Ciudades europeas en América, arquitectura parisina',
    architecture: 'Art nouveau francés, neoclásica, italiana',
    climate: 'Templado',
    people_style: 'Población de ascendencia europea',
    environment: 'Pampas, jacarandás, plazas arboladas',
    colors: 'Gris parisino, verde jacarandá, azul celeste',
    flags_allowed: ['bandera argentina (celeste y blanco con sol)'],
    flags_forbidden: ['bandera uruguaya', 'bandera chilena'],
    skyline_forbidden: ['São Paulo', 'Santiago']
  },
  'Chile': {
    code: 'CL', region: 'Sudamérica',
    city_style: 'Ciudades lineales entre montañas y mar',
    architecture: 'Colonial chilena, modernista, construcción antisísmica',
    climate: 'Mediterráneo en centro',
    people_style: 'Población mestiza, ascendencia europea',
    environment: 'Cordillera de los Andes, costa del Pacífico',
    colors: 'Azul Pacífico, blanco andino, terracota',
    flags_allowed: ['bandera chilena (azul, blanco, rojo con estrella)'],
    flags_forbidden: ['bandera texana', 'bandera cubana'],
    skyline_forbidden: ['Buenos Aires', 'Lima']
  },
  'Perú': {
    code: 'PE', region: 'Sudamérica',
    city_style: 'Ciudades costeras y andinas con mezcla colonial-moderna',
    architecture: 'Colonial española, inca integrada, autoconstrucción',
    climate: 'Desértico en costa, andino frío en sierra',
    people_style: 'Población indígena y mestiza',
    environment: 'Andes, desierto costero, ruinas precolombinas',
    colors: 'Ocre desértico, rojo arcilla, verde andino',
    flags_allowed: ['bandera peruana (rojo y blanco)'],
    flags_forbidden: ['bandera boliviana', 'bandera ecuatoriana'],
    skyline_forbidden: ['Santiago', 'Bogotá']
  },
  'Ecuador': {
    code: 'EC', region: 'Sudamérica',
    city_style: 'Ciudades andinas compactas con centros coloniales',
    architecture: 'Colonial española, republicana',
    climate: 'Ecuatorial templado en sierra',
    people_style: 'Población indígena kichwa, mestiza',
    environment: 'Volcanes, páramos, selva amazónica',
    colors: 'Amarillo andino, azul volcánico, verde selva',
    flags_allowed: ['bandera ecuatoriana (amarillo, azul, rojo con escudo)'],
    flags_forbidden: ['bandera colombiana', 'bandera venezolana'],
    skyline_forbidden: ['Bogotá', 'Lima']
  },
  'Bolivia': {
    code: 'BO', region: 'Sudamérica',
    city_style: 'Ciudades altiplánicas con arquitectura de ladrillo',
    architecture: 'Colonial andina, neo-andina colorida',
    climate: 'Altiplánico frío y seco',
    people_style: 'Población indígena aymara y quechua, vestimenta tradicional',
    environment: 'Altiplano, salares, lago Titicaca',
    colors: 'Ocre altiplánico, rojo ladrillo, azul índigo',
    flags_allowed: ['bandera boliviana (rojo, amarillo, verde)', 'wiphala'],
    flags_forbidden: ['bandera peruana', 'bandera chilena'],
    skyline_forbidden: ['Lima', 'Santiago']
  },
  'Uruguay': {
    code: 'UY', region: 'Sudamérica',
    city_style: 'Ciudades compactas con arquitectura europea',
    architecture: 'Neoclásica, art déco, colonial española',
    climate: 'Templado oceánico',
    people_style: 'Población de ascendencia europea',
    environment: 'Playas atlánticas, praderas, río de la Plata',
    colors: 'Celeste uruguayo, blanco arena, verde pradera',
    flags_allowed: ['bandera uruguaya (celeste, blanco con sol)'],
    flags_forbidden: ['bandera argentina'],
    skyline_forbidden: ['Buenos Aires', 'São Paulo']
  },
  'Paraguay': {
    code: 'PY', region: 'Sudamérica',
    city_style: 'Ciudades de baja densidad con arquitectura modesta',
    architecture: 'Colonial española simple, modernista paraguayo',
    climate: 'Subtropical húmedo, caluroso',
    people_style: 'Población mestiza guaraní, bilingüe',
    environment: 'Ríos Paraguay y Paraná, llanuras',
    colors: 'Rojo arcilla, verde subtropical, azul fluvial',
    flags_allowed: ['bandera paraguaya (rojo, blanco, azul con escudo)'],
    flags_forbidden: ['bandera argentina', 'bandera brasileña'],
    skyline_forbidden: ['Buenos Aires', 'São Paulo']
  },
  'República Dominicana': {
    code: 'DO', region: 'Caribe',
    city_style: 'Ciudades caribeñas con zonas coloniales históricas',
    architecture: 'Colonial española siglo XVI, modernista caribeño',
    climate: 'Tropical cálido, húmedo',
    people_style: 'Población afrocaribeña y mulata',
    environment: 'Playas de arena blanca, palmeras, mar Caribe',
    colors: 'Azul caribeño, amarillo sol, verde palma',
    flags_allowed: ['bandera dominicana (azul, blanco, rojo con cruz)'],
    flags_forbidden: ['bandera haitiana', 'bandera puertorriqueña'],
    skyline_forbidden: ['San Juan', 'La Habana']
  },
  'Haití': {
    code: 'HT', region: 'Caribe',
    city_style: 'Ciudades densas e informales con arquitectura autoconstruida',
    architecture: 'Colonial francesa deteriorada, construcción improvisada',
    climate: 'Tropical cálido',
    people_style: 'Población afrocaribeña',
    environment: 'Colinas deforestadas, mercados callejeros',
    colors: 'Terracota polvoriento, azul desteñido, ocre',
    flags_allowed: ['bandera haitiana (azul y rojo)'],
    flags_forbidden: ['bandera dominicana'],
    skyline_forbidden: ['Santo Domingo']
  },
  'Puerto Rico': {
    code: 'PR', region: 'Caribe',
    city_style: 'Ciudades caribeñas-americanas con zona colonial',
    architecture: 'Colonial española, art déco caribeño, suburbios americanos',
    climate: 'Tropical marítimo',
    people_style: 'Población latina-caribeña con influencia estadounidense',
    environment: 'Playas, selva tropical (El Yunque)',
    colors: 'Azul caribeño, amarillo tropical, verde selva',
    flags_allowed: ['bandera puertorriqueña (rojo, blanco, azul)', 'bandera estadounidense'],
    flags_forbidden: ['bandera dominicana'],
    skyline_forbidden: ['Miami', 'Nueva York']
  },
  'Costa Rica': {
    code: 'CR', region: 'América Central',
    city_style: 'Ciudades compactas de baja altura, zonas verdes',
    architecture: 'Modernista tropical, construcción sismorresistente',
    climate: 'Tropical lluvioso, biodiverso',
    people_style: 'Población mestiza, estilo casual',
    environment: 'Selva tropical, volcanes, biodiversidad',
    colors: 'Verde selva, azul volcánico, amarillo tropical',
    flags_allowed: ['bandera costarricense (azul, blanco, rojo)'],
    flags_forbidden: ['bandera nicaragüense', 'bandera panameña'],
    skyline_forbidden: ['Ciudad de Panamá']
  },
  'Panamá': {
    code: 'PA', region: 'América Central',
    city_style: 'Ciudad de rascacielos modernos junto al canal',
    architecture: 'Rascacielos de vidrio, colonial española (Casco Viejo)',
    climate: 'Tropical marítimo',
    people_style: 'Población diversa, internacional',
    environment: 'Canal de Panamá, océanos, selva tropical',
    colors: 'Azul marino, vidrio reflejante, verde selva',
    flags_allowed: ['bandera panameña (blanco, rojo, azul con estrellas)'],
    flags_forbidden: ['bandera costarricense', 'bandera colombiana'],
    skyline_forbidden: ['Miami', 'Bogotá']
  },
  'Honduras': {
    code: 'HN', region: 'América Central',
    city_style: 'Ciudades centroamericanas con arquitectura modesta',
    architecture: 'Colonial española limitada, modernista simple',
    climate: 'Tropical cálido',
    people_style: 'Población mestiza e indígena',
    environment: 'Montañas, costa caribeña, ruinas mayas',
    colors: 'Verde montaña, azul caribeño, terracota',
    flags_allowed: ['bandera hondureña (azul y blanco con estrellas)'],
    flags_forbidden: ['bandera salvadoreña', 'bandera guatemalteca'],
    skyline_forbidden: ['Guatemala City', 'San Salvador']
  },
  'Guatemala': {
    code: 'GT', region: 'América Central',
    city_style: 'Ciudades coloniales en valles volcánicos',
    architecture: 'Colonial española barroca, maya integrada',
    climate: 'Tropical de altura',
    people_style: 'Población maya mayoritaria, vestimenta tradicional vibrante',
    environment: 'Volcanes, lagos de montaña (Atitlán), ruinas mayas',
    colors: 'Textiles multicolores mayas, azul volcánico, verde montaña',
    flags_allowed: ['bandera guatemalteca (azul celeste y blanco)'],
    flags_forbidden: ['bandera mexicana', 'bandera hondureña'],
    skyline_forbidden: ['Ciudad de México', 'San Salvador']
  },
  'El Salvador': {
    code: 'SV', region: 'América Central',
    city_style: 'Ciudades densas en valles volcánicos',
    architecture: 'Modernista salvadoreño, reconstrucción post-terremoto',
    climate: 'Tropical cálido, volcánico',
    people_style: 'Población mestiza',
    environment: 'Volcanes, costa Pacífico, lagos de cráter',
    colors: 'Azul volcánico, verde plantación, terracota',
    flags_allowed: ['bandera salvadoreña (azul y blanco con escudo)'],
    flags_forbidden: ['bandera hondureña', 'bandera guatemalteca'],
    skyline_forbidden: ['Guatemala City', 'Tegucigalpa']
  },
  'Nicaragua': {
    code: 'NI', region: 'América Central',
    city_style: 'Ciudades coloniales y lagos',
    architecture: 'Colonial española, modernista nicaragüense',
    climate: 'Tropical cálido, volcánico',
    people_style: 'Población mestiza',
    environment: 'Lagos (Nicaragua, Managua), volcanes',
    colors: 'Azul lacustre, verde tropical, terracota',
    flags_allowed: ['bandera nicaragüense (azul y blanco con escudo)'],
    flags_forbidden: ['bandera costarricense', 'bandera hondureña'],
    skyline_forbidden: ['San José', 'Ciudad de Panamá']
  }
};
